### ISSUE TITLE
Tor Repo Moved

### ISSUE THREAD

**Issue by robkerry** [TeamHG-Memex/aquarium#2]
The build now fails as `usertaken/tor-socks-proxy` was moved to `0xj9/tor-socks-proxy`.

Changing the repo name in [docker-compose.yml](https://github.com/TeamHG-Memex/aquarium/blob/master/%7B%7Bcookiecutter.folder_name%7D%7D/docker-compose.yml) fixes this.

**Comment by kmike** [comment]
Ouch, I noticed this a year later :) docker-compose now uses another tor proxy. Thanks for the heads up!
